import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, json, decimal, boolean, longtext } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// Documents table - stores metadata for uploaded research documents
export const documents = mysqlTable("documents", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  fileName: varchar("fileName", { length: 255 }).notNull(),
  s3Key: varchar("s3Key", { length: 512 }).notNull(),
  s3Url: varchar("s3Url", { length: 512 }).notNull(),
  mimeType: varchar("mimeType", { length: 100 }),
  fileSize: int("fileSize"), // in bytes
  tokenCount: int("tokenCount"), // estimated token count for the document
  uploadedAt: timestamp("uploadedAt").defaultNow().notNull(),
  processedAt: timestamp("processedAt"),
  status: mysqlEnum("status", ["uploading", "processing", "completed", "failed"]).default("uploading").notNull(),
  processingError: text("processingError"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Document = typeof documents.$inferSelect;
export type InsertDocument = typeof documents.$inferInsert;

// Document summaries - structured summaries extracted by Qwen2.5-1M
export const documentSummaries = mysqlTable("documentSummaries", {
  id: int("id").autoincrement().primaryKey(),
  documentId: int("documentId").notNull(),
  keyClaims: json("keyClaims"), // Array of key claims extracted from document
  entities: json("entities"), // Array of entities (names, organizations, concepts)
  dates: json("dates"), // Array of important dates mentioned
  contradictions: json("contradictions"), // Array of contradictions with other documents
  confidenceScores: json("confidenceScores"), // Confidence levels for each claim
  summary: longtext("summary"), // Full text summary
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type DocumentSummary = typeof documentSummaries.$inferSelect;
export type InsertDocumentSummary = typeof documentSummaries.$inferInsert;

// Retrieval results - stores results from MEGA-RAG retrieval system
export const retrievalResults = mysqlTable("retrievalResults", {
  id: int("id").autoincrement().primaryKey(),
  queryId: varchar("queryId", { length: 128 }).notNull(),
  documentId: int("documentId").notNull(),
  chunkId: varchar("chunkId", { length: 128 }).notNull(),
  chunkText: longtext("chunkText"),
  retrievalSource: mysqlEnum("retrievalSource", ["vector", "bm25", "graphrag"]).notNull(),
  relevanceScore: decimal("relevanceScore", { precision: 5, scale: 4 }), // 0.0000 to 1.0000
  cragScore: decimal("cragScore", { precision: 5, scale: 4 }), // CRAG evaluator score
  trustScore: decimal("trustScore", { precision: 5, scale: 4 }), // RE-RAG trust classifier score
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type RetrievalResult = typeof retrievalResults.$inferSelect;
export type InsertRetrievalResult = typeof retrievalResults.$inferInsert;

// Synthesis queries - stores research queries submitted by users
export const synthesisQueries = mysqlTable("synthesisQueries", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  query: longtext("query").notNull(),
  decomposedQueries: json("decomposedQueries"), // Sub-queries generated by Boss Agent
  status: mysqlEnum("status", ["pending", "processing", "completed", "failed"]).default("pending").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  completedAt: timestamp("completedAt"),
});

export type SynthesisQuery = typeof synthesisQueries.$inferSelect;
export type InsertSynthesisQuery = typeof synthesisQueries.$inferInsert;

// Synthesis reports - final synthesis results with claim grounding
export const synthesisReports = mysqlTable("synthesisReports", {
  id: int("id").autoincrement().primaryKey(),
  queryId: int("queryId").notNull(),
  reportContent: longtext("reportContent"), // Full synthesis report in markdown
  claims: json("claims"), // Array of claims with source attribution
  contradictions: json("contradictions"), // Array of detected contradictions
  confidenceMetrics: json("confidenceMetrics"), // Overall confidence metrics
  halluccinationScore: decimal("halluccinationScore", { precision: 5, scale: 4 }), // Estimated hallucination rate
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SynthesisReport = typeof synthesisReports.$inferSelect;
export type InsertSynthesisReport = typeof synthesisReports.$inferInsert;

// Claims - individual claims extracted from synthesis with source grounding
export const claims = mysqlTable("claims", {
  id: int("id").autoincrement().primaryKey(),
  reportId: int("reportId").notNull(),
  claimText: longtext("claimText").notNull(),
  sourceChunkIds: json("sourceChunkIds"), // Array of chunk IDs that support this claim
  confidenceTier: mysqlEnum("confidenceTier", ["high", "medium", "low"]).notNull(),
  supportingDocuments: json("supportingDocuments"), // Array of document IDs that support this claim
  contradictingDocuments: json("contradictingDocuments"), // Array of document IDs that contradict this claim
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Claim = typeof claims.$inferSelect;
export type InsertClaim = typeof claims.$inferInsert;

// Contradictions - detected contradictions between sources
export const contradictions = mysqlTable("contradictions", {
  id: int("id").autoincrement().primaryKey(),
  reportId: int("reportId").notNull(),
  claim1: longtext("claim1").notNull(),
  claim2: longtext("claim2").notNull(),
  source1DocumentId: int("source1DocumentId").notNull(),
  source2DocumentId: int("source2DocumentId").notNull(),
  severity: mysqlEnum("severity", ["high", "medium", "low"]).notNull(),
  resolution: text("resolution"), // How the contradiction was resolved
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Contradiction = typeof contradictions.$inferSelect;
export type InsertContradiction = typeof contradictions.$inferInsert;

// Knowledge graph entities - entities extracted from documents
export const entities = mysqlTable("entities", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  type: varchar("type", { length: 100 }), // person, organization, concept, location, etc.
  description: text("description"),
  mentionCount: int("mentionCount").default(1),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Entity = typeof entities.$inferSelect;
export type InsertEntity = typeof entities.$inferInsert;

// Entity relationships - relationships between entities in the knowledge graph
export const entityRelationships = mysqlTable("entityRelationships", {
  id: int("id").autoincrement().primaryKey(),
  entity1Id: int("entity1Id").notNull(),
  entity2Id: int("entity2Id").notNull(),
  relationshipType: varchar("relationshipType", { length: 100 }).notNull(), // e.g., "works_at", "founded_by"
  strength: decimal("strength", { precision: 5, scale: 4 }), // 0.0 to 1.0
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type EntityRelationship = typeof entityRelationships.$inferSelect;
export type InsertEntityRelationship = typeof entityRelationships.$inferInsert;

// Performance metrics - tracks system performance and hallucination rates
export const performanceMetrics = mysqlTable("performanceMetrics", {
  id: int("id").autoincrement().primaryKey(),
  metricType: varchar("metricType", { length: 100 }).notNull(), // e.g., "hallucination_rate", "retrieval_quality", "synthesis_time"
  value: decimal("value", { precision: 10, scale: 4 }),
  queryId: int("queryId"),
  reportId: int("reportId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PerformanceMetric = typeof performanceMetrics.$inferSelect;
export type InsertPerformanceMetric = typeof performanceMetrics.$inferInsert;